defmodule Hachiware.Reports.Repo.Migrations.UpdatedSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS public")

    create table(:reports, primary_key: false, prefix: "public") do
      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')"),
        primary_key: true
      )

      add(:type, :text, null: false)
      add(:command, :text)
      add(:name, :text)
      add(:original_filename, :text)
      add(:patched_content, :text)
      add(:policy_compliance, :map)
      add(:changes_summary, :map)
      add(:violations_analysis, :map)
      add(:validation_details, :map)
      add(:policy_details, :map)
      add(:timing, :map)
    end
  end

  def down do
    drop(table(:reports, prefix: "public"))
  end
end
