defmodule Hachiware.Reports.Repo.Migrations.UpdatedSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reports, primary_key: false) do
      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')"),
        primary_key: true
      )

      add(:original_filename, :text, null: false)
      add(:patched_content, :text, null: false)
      add(:policy_compliance, :map)
      add(:changes_summary, :map)
      add(:violations_analysis, :map)
      add(:validation_details, :map)
      add(:policy_details, :map)
      add(:timing, :map)
    end

    create table(:command, primary_key: false) do
      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')"),
        primary_key: true
      )

      add(:command, :text, null: false)
    end
  end

  def down do
    drop(table(:command))

    drop(table(:reports))
  end
end
