defmodule Hachiware.Reports.Repo.Migrations.AddReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reports, primary_key: false) do
      add(:created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')"),
        primary_key: true
      )

      add(:title, :text, null: false)
      add(:report, :text, null: false)
      add(:status, :text, default: "open")
    end
  end

  def down do
    drop(table(:reports))
  end
end
